### PR TITLE
MTLModel: fix memory leak caused by -validateValue:forKey:.

### PR DESCRIPTION
**Pull request by mkimi-lightricks**
`-[NSObject validateValue:forKey:]` is leaking since iOS11. This feature isn't used by any of you apps, hence it's removed.

### CODE REVIEW

**Comment by StatusReport** [comment]
Can't we just get rid of `MTLValidateAndSetValue` completely?

**Comment by mkimi-lightricks** [comment]
Nope, this logic is used to set values for a key in `MTLModel` class.

**Comment by StatusReport** [comment]
Why can't you just call `-setValue:forKey:` instead of the call? Right now there's overhead (because of the exception handling), plus the method call doesn't validate, but only sets the value.

**Comment by mkimi-lightricks** [comment]
The reason for the change is to get rid of the memory leak. I wasn't planning to piggyback any other changes, since they were not coordinated with (and tested by) our tech-leads.

As to the code changes. I've tried to change as little code as possible in order to limit the divergence, of our fork from the main repo, to minimum. Hence I didn't wanna make any name, doc changes. Initially I even considered just to comment out the problematic line with addition of an explanation comment.

**Comment by StatusReport** [comment]
@mkimi-lightricks ping.

I still think we should just drop the validation completely, and just set the value if the pointer equality fails.

**Comment by mkimi-lightricks** [comment]
I will definitely do that. I had some troubles with running the tests locally.

**Comment by mkimi-lightricks** [comment]
@StatusReport 

I performed the *leak checking* flow on iOS12 simulator (Phoenix app) and this issue isn't present.

Just FYI.

**Comment by mkimi-lightricks** [comment]
Since the leak is fixed in iOS12, and in iOS 11 it doesn't affect the overall stability of our apps I'm closing this PR.

**Pull request closed without merging**
